name: Pull Request
on:
  pull_request:
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: npm i
      - name: Run eslint
        run: npm run lint
