name: Pull Request
on:
  pull_request:
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PORT: "4000"
          envkey_POSTGRES_USERNAME: "postgres"
          envkey_POSTGRES_PASSWORD: "272410"
          envkey_POSTGRES_HOST: "localhost"
          envkey_POSTGRES_PORT: "5432"
          envkey_POSTGRES_DATABASE: "coasterDB"
          envkey_DATABASE_URL: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public"
          file_name: .env
      - name: Run eslint
        run: npm run lint
      - name: Build
        run: npm i && npm run build
